# This is a basic workflow to help you get started with Actions

name: DOCKER-PP

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

    build:
      runs-on: ubuntu-latest
      container:
        image: pratikkawane/ppp
        credentials:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
      steps:
      - name: hello
        run: echo hello
