# This is a basic workflow to help you get started with Actions

name: DEMO

# Controls when the workflow will run
on:
 

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-workflow-passing-data:
    uses: pratikkawane/reusableworkflow/.github/workflows/reusable.yml@main
  
