# This is a basic workflow to help you get started with Actions

name: DOCKER-DEMO-1

# Controls when the workflow will run
on:
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  
  container:
    runs-on: ubuntu-latest
    container: httpd

    steps:
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
        name: Run in container
