name: docker image testing 

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: docker build  
        run : |
           echo  ${{ secrets.DOCKER_SECRET }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
           docker build -t app .
           docker tag app pratikkawane/private
           docker push pratikkawane/private

  
