
# This is a basic workflow to help you get started with Actions

name: Pratik-public

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   
 container-test-job:
    runs-on: ubuntu-latest
    container:
      image: pratikkawane/myimage
    steps:
        - name:  docker-login
          run: |
           echo  ${{ secrets.DOCKER_SECRET }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        - uses: actions/checkout@v3
        - name: Run a multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
